### PR TITLE
add coffee-script generation with a --coffee option

### PR DESCRIPTION
**Pull request by ebourmalo**
Added '--coffee' generator option for generating coffeescript files instead of javascript files.
Tests have been added to make sure the original list of files to generate are exactly the same than before.

Relative to the [issue #1923](https://github.com/balderdashy/sails/issues/1923)

### CODE REVIEW

**Comment by ebourmalo** [comment]
The tests cover all cases but if you don't like the build method, we can return to something more static as before @mikermcneil @konstantinzolotarev :)

**Comment by ebourmalo** [comment]
Up :) @mikermcneil @konstantinzolotarev

**Comment by konstantinzolotarev** [comment]
@ebourmalo testing testing testing =D

**Comment by ebourmalo** [comment]
@konstantinzolotarev Awesome :) Is it going well?
Let me know if I can help.

**Comment by ebourmalo** [comment]
@konstantinzolotarev up :)

**Comment by konstantinzolotarev** [comment]
@ebourmalo Sorry for a long delay. 
I moved this to new repo: https://github.com/balderdashy/sails-generate-backend-coffee

Could you please take a look there. If all is ok in coffee scripts ?

**Comment by ebourmalo** [comment]
hey @konstantinzolotarev 
If you copied the coffee files you were interested in, it will be ok ;)

**Comment by sgress454** [comment]
Hi @ebourmalo, sorry for the long delay on getting to this.  The fact is that this is the kind of use case that drove us to build generators as separate modules in the first place.  What I mean is that instead of a PR to `sails-generate-backend`, this should be a completely separate generator: `sails-generate-backend-coffee`.  You would then add something like this to a `.sailsrc` file in your home directory:

```
"generators": {
   "modules": {
      "backend": "sails-generate-backend-coffee"
   }
}
```
and in that same home folder do `npm install sails-generate-backend-coffee`, and presto: every time you run `sails new` from then on, you'd get coffeescript files.  See [sails-generate-frontend-angular](https://www.npmjs.com/package/sails-generate-frontend-angular) as an example of another such generator override.

The good news is, I think you're pretty much done; all you'd need to make this a separate generator is to take out the logic that switches between coffee and regular templates (since it'd always be coffee).

**Pull request closed without merging**
