### PR TITLE
Example connections should be commented

### LINKED ISSUE #31: config/connections.js configures default invalid connections for new projects
Within `templates/config/connections.js`, this file actually defines default connections.

https://github.com/balderdashy/sails-generate-backend/blob/v0.12.4/templates/config/connections.js

These should be commented out by default, especially since most of them require additional npm packages to be installed.

After creating a new project and defining our mongo configuration into `config/env/development.js`, we kept seeing issues where on `sails lift` it was attempting to access a mongo server on localhost. 

I assume that since these connections are defined here and even though we were not actually using them, on sails lift, it attempts to connect to these.

I would recommend that they be commented out by default and possibly leaving just sails-disk uncommented since this is the default on a new install anyways.

### PR DESCRIPTION
**Pull request by animedbz16**
This should fix #31.

### CODE REVIEW

**Comment by sgress454** [comment]
What you experienced in #31 is documented as a note [here](http://sailsjs.org/documentation/reference/configuration/sails-config-connections#?multiple-connections-for-an-adapter), but commenting the default connection configs would solve that issue and make this more in line with our other config files.  Would like to hear @mikermcneil 's opinion but looks good to me.

**Comment by sgress454** [comment]
Only thing I might add is that since we already had some of the mongo config commented out (to make it clearer that they're optional), you might put extra comments _after_ those lines (and the password configs for postgres and mysql as well), e.g.:

```

  // someMongodbServer: {
  //   adapter: 'sails-mongo',
  //   host: 'localhost',
  //   port: 27017,
  //   user: 'username', // optional
  //   password: 'password', // optional
  //   database: 'your_mongo_db_name_here' // optional
  // },

**Comment by particlebanana** [comment]
@sgress454 LGTM

**Comment by animedbz16** [comment]
@sgress454 I've made the suggested changes to include the optional verbiage for the user/password/database options. Please review for accuracy.

**Comment by sgress454** [comment]
Thanks @animedbz16!

**Comment by animedbz16** [comment]
@sgress454 Just created a new sails project under sails v0.12.1. It doesn't seem like these updates were tagged into a release in git or published to npm. Any updates on when that will occur?

**Comment by sgress454** [comment]
Hi @animedbz16 sorry about that -- needed to wait for Sails v0.12.2 to publish because some of the updated examples in the commented configs were relying on bug fixes in Sails.  Just published new version of sails-generate-backend, so we should be good to go!

**Pull request merged**
